apiVersion: v1
kind: Service
metadata:
  name: ejblb-headless-svc
spec:
  clusterIP: None
  ports:
  - name: tcp-remote
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcp-9990
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    service: ejblb
  sessionAffinity: None
  type: ClusterIP
 