apiVersion: v1
kind: Service
metadata:
  name: ejbclient-headless-svc
spec:
  clusterIP: None
  ports:
  - name: tcp-remote
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: tcp-9990
    port: 9990
    protocol: TCP
    targetPort: 9990 
  selector:
    application: ejbclient
  sessionAffinity: None
  type: ClusterIP
 
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ejbclient
  labels:
    application: ejbclient 
spec:
  replicas: 1
  selector:
    matchLabels: 
      application: ejbclient
  serviceName:  ejbclient-headless-svc    
  template:
    metadata: 
      labels: 
        application: ejbclient
    spec:      
      volumes:
        - name: ejbclient-volume
          emptyDir: {}
      containers:
        - name: ejbclient
          image: 'ghcr.io/robert0714/cluster-example-client:latest'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Taipei            
            - name: JAVA_OPTS
              value: >-
                -Dwildfly.statistics-enabled=true
                -Djboss.bind.address=0.0.0.0 
                -Xms300m 
                -Xmx600m
                -Drmote.ejb.hostsAndPorts[0]=ejblb-0.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[1]=ejblb-1.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[2]=ejblb-2.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[3]=ejblb-3.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[4]=ejblb-4.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[5]=ejblb-5.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[6]=ejblb-6.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[7]=ejblb-7.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[8]=ejblb-8.ejblb-headless-svc:8080
                -Drmote.ejb.hostsAndPorts[9]=ejblb-9.ejblb-headless-svc:8080
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace            
            - name: STATEFULSET_HEADLESS_SERVICE_NAME
              value: ejbclient-headless-svc
            - name: JAVA_ARGS
              value: >-
                -Djboss.server.data.dir=/opt/jboss/container/wildfly-bootable-jar-data/standalone/data
                --install-dir=/opt/jboss/container/wildfly-bootable-jar-server
            - name: JBOSS_HOME
              value: /opt/jboss/container/wildfly-bootable-jar-server
          resources:
            limits:
              cpu: 800m
              memory: 700Mi
            requests:
              cpu: 400m
              memory: 300Mi              
          volumeMounts:
            - name: ejbclient-volume
              mountPath: /opt/jboss/container/wildfly-bootable-jar-data/standalone/data
              