kind: Deployment
apiVersion: apps/v1
metadata:
  name:  hal-deploy
  labels:
    application: hal
spec:
  replicas: 1
  selector:
    matchLabels:
      application: hal
  template:
    metadata:
      labels:
        application: hal
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name:  hal
        image: 'quay.io/halconsole/hal:3.5.12.Final'
        imagePullPolicy: Always
        ports: 
            - containerPort: 9090
              protocol: TCP 
        env:
        - name: MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName:  hal
              resource: requests.memory
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName:  hal
              resource: limits.memory 
        resources:
          requests: 
            memory: 300Mi
            cpu: 200m
          limits: 
            memory: 700Mi
            cpu: 400m
---
apiVersion: v1
kind: Service
metadata:
  name: hal-service
spec:
  ports:
  - name: tcp-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    application: hal
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hal-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 9090
      name: tcp-9090
      protocol: TCP
    hosts:
    - 'hal-istio-system.apps.ocp.iisi.test'  
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: hal-vs 
spec:
  hosts:
    - hal-service
  tcp:
    - route:
        - destination:
            host: hal-service
